#!/usr/bin/env node
// Builds the tokens-only design-system package under .design-sync/pkg/ from
// the site's single source of truth, index.html:
//   • pkg/styles.css  ← the page's <style> block, minus the GSAP-gated
//                       ".anim …" reveal rules (inert without the page script
//                       and misleading to a design agent), prefixed with
//                       @font-face rules pointing at pkg/fonts/.
//   • pkg/fonts/*.woff2 ← Google Fonts latin subsets for the families the
//                       page loads. Downloaded ONLY when a file is missing
//                       (the files are committed, so a normal run is offline).
// Run from the repo root: node .design-sync/extract.mjs
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..');
const PKG = join(HERE, 'pkg');
const FONTS_DIR = join(PKG, 'fonts');

// Families the page loads (mirrors the Google Fonts <link> in index.html).
// Weight ranges are the variable-font axes requested there.
const FONTS = [
  { family: 'Fraunces', style: 'normal', weight: '400 700', file: 'fraunces-normal-latin.woff2' },
  { family: 'Fraunces', style: 'italic', weight: '400 600', file: 'fraunces-italic-latin.woff2' },
  { family: 'Nunito Sans', style: 'normal', weight: '300 800', file: 'nunito-sans-normal-latin.woff2' },
  { family: 'Nunito Sans', style: 'italic', weight: '400 600', file: 'nunito-sans-italic-latin.woff2' },
];
// A modern-browser UA makes Google return woff2 variable fonts per subset.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const html = readFileSync(join(REPO, 'index.html'), 'utf8');

// ── 1. page CSS ────────────────────────────────────────────────────────────
const styleBlocks = [...html.matchAll(/<style>([\s\S]*?)<\/style>/g)];
if (styleBlocks.length !== 1) {
  console.error(`[extract] expected exactly one <style> block in index.html, found ${styleBlocks.length}`);
  process.exit(1);
}
let css = styleBlocks[0][1];
const REVEAL_START = '/* ---------- reveal (only when .anim) ---------- */';
const REVEAL_END = '/* ---------- responsive ---------- */';
const a = css.indexOf(REVEAL_START), b = css.indexOf(REVEAL_END);
if (a < 0 || b < 0 || b < a) {
  console.error('[extract] reveal-block markers not found in index.html CSS — update REVEAL_START/REVEAL_END in extract.mjs');
  process.exit(1);
}
css = css.slice(0, a) + css.slice(b);
// Dedent the two-space indentation the <style> block carries.
css = css.split('\n').map((l) => l.replace(/^  /, '')).join('\n').trim() + '\n';

// ── 2. fonts ───────────────────────────────────────────────────────────────
const missing = FONTS.filter((f) => !existsSync(join(FONTS_DIR, f.file)));
if (missing.length) {
  const link = html.match(/href="(https:\/\/fonts\.googleapis\.com\/css2\?[^"]+)"/)?.[1]?.replace(/&amp;/g, '&');
  if (!link) { console.error('[extract] Google Fonts <link> not found in index.html'); process.exit(1); }
  console.error(`[extract] ${missing.length} font file(s) missing — fetching from Google Fonts`);
  const gcss = await (await fetch(link, { headers: { 'User-Agent': UA } })).text();
  // Blocks are preceded by a "/* <subset> */" comment; keep the latin ones.
  const blocks = [...gcss.matchAll(/\/\* (\w[\w-]*) \*\/\s*@font-face\s*\{([^}]+)\}/g)]
    .filter((m) => m[1] === 'latin')
    .map((m) => m[2]);
  mkdirSync(FONTS_DIR, { recursive: true });
  for (const f of missing) {
    const body = blocks.find((bd) =>
      bd.includes(`font-family: '${f.family}'`) && bd.includes(`font-style: ${f.style}`));
    const url = body?.match(/url\(([^)]+\.woff2)\)/)?.[1];
    if (!url) { console.error(`[extract] no latin woff2 for ${f.family} ${f.style} in Google CSS`); process.exit(1); }
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    writeFileSync(join(FONTS_DIR, f.file), buf);
    console.error(`  fonts/${f.file} (${(buf.length / 1024).toFixed(0)} KB)`);
  }
}
const fontFaces = FONTS.map((f) =>
  `@font-face{font-family:"${f.family}";font-style:${f.style};font-weight:${f.weight};font-display:swap;src:url("./fonts/${f.file}") format("woff2")}`,
).join('\n');

// ── 3. write ───────────────────────────────────────────────────────────────
const out = [
  '/* GENERATED by .design-sync/extract.mjs from index.html — do not edit; edit index.html and re-run. */',
  '',
  '/* ---------- fonts (Fraunces = display serif, Nunito Sans = body) ---------- */',
  fontFaces,
  '',
  css,
].join('\n');
writeFileSync(join(PKG, 'styles.css'), out);
console.error(`[extract] pkg/styles.css written (${(out.length / 1024).toFixed(0)} KB)`);
